### PR TITLE
Updated version bug in the title

### PR DESCRIPTION
**Pull request by thesteve0**

### CODE REVIEW

**Comment by jsvgoncalves** [comment]
@thesteve0 care to squash into a single commit?

**Comment by jsvgoncalves** [comment]
Merged with 28d5687

**Comment by thesteve0** [comment]
Thanks - I was just getting to rebase when I notice you merged. I will do the rebase next time.

**Comment by jsvgoncalves** [comment]
@thesteve0 No worries, thought it's not worth the hassle so I just did it quickly

**Pull request closed without merging**
