### PR TITLE
Fix #77, add the timeline for version 3.6

### LINKED ISSUE #77: It's time to update the content for version 3.6
https://github.com/openshift/origin/releases/tag/v3.6.0

### PR DESCRIPTION
**Pull request by warmchang**

### CODE REVIEW

**Comment by wgordon17** [comment]
openshift_origin_-_open_source_container_application_platform

Additional padding is needed in the illustrated places to maintain consistent spacing, and also to reveal some slightly hidden text.

Thanks!

**Comment by warmchang** [comment]
Fixed and tested in my local envirments, please check it, thanks!

**Review by wgordon17 — CHANGES_REQUESTED** [review]
Please see the screenshot comments

**Comment by warmchang** [comment]
I don't understand, any problem with my revised commit and the screenshot? 🤔

**Review by wgordon17 — APPROVED** [review]

**Comment by wgordon17** [comment]
I'm sorry, I completely glossed over the fact that you had already updated this.
Thanks, that looks great!

**Comment by warmchang** [comment]
Welcome!

**Pull request merged**
